orbs:
  docker: circleci/docker@1.5.0
version: 2.1
executors:
  docker-publisher: 
    environment:
      IMAGE_NAME: akshayasharma770/node-test-aks
    docker:
      - image: circleci/node:latest

jobs:
    build:
      executor: docker-publisher
      steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Install dependencies
          command: npm i
    publish: 
      executor: docker-publisher
      steps: 
        - checkout
        - setup_remote_docker
        - run: 
            name: Build Publish Docker Image to Docker Hub
            command: |
              echo "$DOCKERHUB_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
              docker build -t $IMAGE_NAME:$CIRCLE_SHA1 .
              docker push $IMAGE_NAME:$CIRCLE_SHA1
workflows:
  version: 2
  build-master:
    jobs:
       - build
       - publish
